### ISSUE TITLE
ImportError: No module named 'pkg_resources.extern'

### ISSUE THREAD

**Issue by iliv** [djangocon/2017.djangocon.eu#16]
Can't get it to pip-sync on Ubuntu 16.04.01 LTS

```
(env) admin@lab-xenial:~/2017.djangocon.eu$ pip-sync
Uninstalling pkg-resources-0.0.0: 
Successfully uninstalled pkg-resources-0.0.0
Collecting aldryn-apphooks-config==0.2.7
Downloading aldryn_apphooks_config-0.2.7-py2.py3-none-any.whl
Collecting aldryn-boilerplates==0.7.4
Downloading aldryn_boilerplates-0.7.4-py2.py3-none-any.whl
Collecting aldryn-common==1.0.4
Downloading aldryn-common-1.0.4.tar.gz
Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
File "/home/admin/2017.djangocon.eu/env/lib/python3.5/site-packages/pip/req/req_install.py", line 387, in setup_py
 import setuptools  # noqa
File "/home/admin/2017.djangocon.eu/env/lib/python3.5/site-packages/setuptools/__init__.py", line 10, in <module> from setuptools.extern.six.moves import filter, filterfalse, map
File "/home/admin/2017.djangocon.eu/env/lib/python3.5/site-packages/setuptools/extern/__init__.py", line 1, in <module> from pkg_resources.extern import VendorImporter
ImportError: No module named 'pkg_resources.extern' 
```

Note that it is uninstalling pkg_resources first and then complains about a missing module that's part of this package. This doesn't happen on Debian stable as confirmed by moldy from #django@irc.freenode.net

We troubleshooted this issue collectively on #django today but didn't find a solution.

Not sure if you are aware of it, but here it is for your consideration.

Let me know, please, if you know how to work around or fix this problem on Ubuntu Xenial.

**Comment by audiolion** [comment]
It is trying to import setuptools.. in the requirements file it shows:
```
# The following packages are commented out because they are
# considered to be unsafe in a requirements file:
# setuptools                # via aldryn-search, django-polymorphic
```
So it looks like Ubuntu 16.04 doesn't include its own version of setuptools by default so you would need to install that separately because pip-sync won't install it due to it being 'unsafe'

**Comment by iliv** [comment]
It appears that both setuptools and pkg_resources are installed upon creation of venv with virtualenv:

```
admin@lab-xenial:~/2017.djangocon.eu$ virtualenv --python=/usr/bin/python3.5 env
Running virtualenv with interpreter /usr/bin/python3.5
Using base prefix '/usr'
New python executable in /home/admin/2017.djangocon.eu/env/bin/python3.5
Also creating executable in /home/admin/2017.djangocon.eu/env/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
```

```
(env) admin@lab-xenial:~/2017.djangocon.eu$ ls -lah env/lib/python3.5/site-packages/
total 48K
drwxrwxr-x 11 admin admin 4.0K Nov 30 11:28 .
drwxrwxr-x  5 admin admin 4.0K Nov 30 11:28 ..
-rw-rw-r--  1 admin admin  126 Nov 30 11:28 easy_install.py
drwxrwxr-x 11 admin admin 4.0K Nov 30 11:28 pip
drwxrwxr-x  2 admin admin 4.0K Nov 30 11:28 pip-9.0.1.dist-info
drwxrwxr-x  5 admin admin 4.0K Nov 30 11:28 pkg_resources
drwxrwxr-x  2 admin admin 4.0K Nov 30 11:28 pkg_resources-0.0.0.dist-info
drwxrwxr-x  2 admin admin 4.0K Nov 30 11:28 __pycache__
drwxrwxr-x  5 admin admin 4.0K Nov 30 11:28 setuptools
drwxrwxr-x  2 admin admin 4.0K Nov 30 11:28 setuptools-29.0.1.dist-info
drwxrwxr-x  6 admin admin 4.0K Nov 30 11:28 wheel
drwxrwxr-x  2 admin admin 4.0K Nov 30 11:28 wheel-0.30.0a0.dist-info
```

**Comment by audiolion** [comment]
yeah but you need to install setuptools globally I think, and hopefully it falls back to that because pip-sync removes the library.

Overall it seems like pip-sync library doesn't like setuptools and uninstalls it when it sees it. Since the requirements has two packages, django-polymorphic and aldryn-search which use setuptools it causes the error.

So if you have a global install of python3.5 with setuptools 29.0.1 installed I feel like it would fall back on it, but I am not sure. If anything it seems like the issue is one for pip-sync issue tracker though

**Comment by koniiiik** [comment]
> it would fall back

The default in virtualenv has been for at least a few years (and in venv since it was created) that the virtualenv does not fall back to system site-packages.

FWIW, I could reproduce the problem with virtualenv in a Xenial container; somehow, I got it to run by trial and error when I used venv instead, but I have no idea which step exactly made it possible for the setup to finish successfully. In case you're interested, [here's a transcript](https://gist.github.com/koniiiik/3127d7ca0ade2955d5369af91f03ba6a)… It looks like at some point, pip started to pick up wheels, which made it possible for aldryn-common to install without pkg_resources…

**Comment by yakky** [comment]
It's weird as I have xenial on my laptop and desktop and I haven't had issues with it.
Systemwide I have the following relevant packages installed:

python-setuptools:all/xenial 20.7.0-1 uptodate
python-virtualenv:all/xenial 15.0.1+ds-3 uptodate
python-pip-whl:all/xenial-updates 8.1.1-2ubuntu0.4 uptodate
python3-virtualenv:all/xenial 15.0.1+ds-3 uptodate
python3-pkg-resources:all/xenial 20.7.0-1 uptodate
python-pkg-resources:all/xenial 20.7.0-1 uptodate

Does your environment differ from this?
